export const FIRESTORE_COLLECTIONS = {
  bookings: "bookings",
  customers: "customers",
  pricePlans: "price-plans",
  consultants: "consultants",
  accounts: "accounts",
  roles: "roles",
  settings: "settings",
  organizations: "organizations",
  payments: "payments",
  slots: "slots",
  zoomSessions: "zoom-sessions",
  users: "users",
  userZoomCredentials: "user-zoom-credentials",
  userCoupons: "user-coupons",
} as const;
