export const FIRESTORE_COLLECTIONS = {
  bookings: "bookings",
  bookingRatings: "booking-ratings",
  customers: "customers",
  pricePlans: "price-plans",
  consultants: "consultants",
  accounts: "accounts",
  roles: "roles",
  settings: "settings",
  organizations: "organizations",
  payments: "payments",
  slots: "slots",
  zoomSessions: "zoom-sessions",
  users: "users",
  userZoomCredentials: "user-zoom-credentials",
  userCoupons: "user-coupons",
  coupons: "coupons",
  policyRevisions: "policy-revisions",
  policyAgreements: "policy-agreements",
  appraisalReports: "appraisal-reports",
} as const;
