name: CI Setup
description: Common setup for CI jobs

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

    - name: Cache pnpm store
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Generate PandaCSS
      shell: bash
      run: pnpm build:panda

    - name: Generate API client
      shell: bash
      run: pnpm generate
